### ISSUE TITLE
Is this a recursive lookup?

### ISSUE THREAD

**Issue by jhg03a** [rnelson0/puppet-generate-puppetfile#18]
Are the package dependency lookups recursive?  For example in the event that module A requires modules 1,2,3 and module 2 requires module B, does the requirement for module B in the output roll up to the final output?

**Comment by rnelson0** [comment]
Yes, each package is checked out via puppet module tool, which resolves dependencies recursively and uses existing versions if present (for modules after the first). This is done at the time you run `generate-puppetfile` so should be the most recent version allowed per the dependency statement.

**Comment by jhg03a** [comment]
Excellent!
