### ISSUE TITLE
Is it not working? 

### ISSUE THREAD

**Issue by feniix** [rnelson0/puppet-generate-puppetfile#21]
Am I doing something wrong?
![image](https://cloud.githubusercontent.com/assets/91633/13956103/1966384a-f026-11e5-8e94-575937e5b1da.png)

**Comment by rnelson0** [comment]
Hrm, I'm not sure. Here's what I get:

````
[rnelson0@build03 controlrepo:domainjoin]$ be generate-puppetfile --version
generate-puppetfile v0.9.6
[rnelson0@build03 controlrepo:domainjoin]$ be generate-puppetfile echocat/nfs rnelson0/certs

Installing modules. This may take a few minutes.

Your Puppetfile has been generated. Copy and paste between the markers:

=======================================================================
forge 'http://forge.puppetlabs.com'

# Modules discovered by generate-puppetfile
mod 'echocat/nfs', '1.8.1'
mod 'puppetlabs/concat', '1.2.5'
mod 'puppetlabs/stdlib', '4.11.0'
mod 'rnelson0/certs', '0.7.0'
=======================================================================
````
(where `be` is `bundle exec`). It is calling out to `puppet module install`. You can try running `generate-puppetfile -d <args>` or directly calling `puppet module install echocat/nfs` and looking for errors. This tool does swallow up a lot of error messages in its current state, and may still swallow a few even in debug mode.

**Comment by feniix** [comment]
I know what is going on, if puppet is not working for any reason it just fails silently:

![image](https://cloud.githubusercontent.com/assets/91633/13967934/7e008544-f058-11e5-8d6b-aa2103cf67d8.png)

**Comment by rnelson0** [comment]
Yes, that is something that is important and the error should not be
swallowed. I will add this to the roadmap.

-- 

Rob Nelson
rnelson0@gmail.com

**Comment by rnelson0** [comment]
I will track this in #22
