### ISSUE TITLE
Add support for updating from git

### ISSUE THREAD

**Issue by jyaworski** [rnelson0/puppet-generate-puppetfile#25]
Currently, this module only works with the forge versions of modules. Can this also have git functionality? For example, if I want to update all of my modules to the latest HEAD.

Example:

```
mod 'archive',
        :git    => 'https://github.com/voxpupuli/puppet-archive.git',
        :commit => 'f382f2d199574590739394050302f626056ad15e'

mod 'auditd',
        :git    => 'https://github.com/kemra102/puppet-auditd.git',
        :commit => '9958c76401085e96bf1b70bc059770b93c2585a0'
```

``` shell
joseph.yaworski@jyaworski-mbpr ~ % git ls-remote https://github.com/voxpupuli/puppet-archive.git HEAD
24eace7915d1f08148a040d474cf4b2f72558779    HEAD

joseph.yaworski@jyaworski-mbpr ~ % git ls-remote https://github.com/kemra102/puppet-auditd.git HEAD
9958c76401085e96bf1b70bc059770b93c2585a0    HEAD
```

**Comment by rnelson0** [comment]
That's a feature I'd like to have but I cannot make any promises on when I
will have time. PRs welcome, but you already know this!

-- 

Rob Nelson
rnelson0@gmail.com

**Comment by jyaworski** [comment]
I'll see if I can get to it. Would you prefer shelling out or using libgit2?

**Comment by rnelson0** [comment]
Doesn't matter to me. Rubbishy solution seems better.

-- 

Rob Nelson
rnelson0@gmail.com

**Comment by jyaworski** [comment]
OK. Are you amenable to using the puppetforge bindings too, instead of shelling out to puppet?

**Comment by rnelson0** [comment]
Not at this time. Dependency tracking is available but it can be
problematic, such as librarian-puppet shows when it gets stuck in a
dependency traversal loop. The PMT seems to have a 100% success rate, so
though it's time consuming, it also means less bugs to deal with. Maybe we
can revisit it later.


Rob Nelson
rnelson0@gmail.com

**Comment by rnelson0** [comment]
@jyaworski As always, I welcome any PRs that add this support! However, I am closing this issue, we can open a new one if either of us finds time to add this. Thanks!
