### ISSUE TITLE
Add Windows support

### ISSUE THREAD

**Issue by jhg03a** [rnelson0/puppet-generate-puppetfile#28]
```
generate-puppetfile jhg03a/accountfacts -d

Processing modules from the command line...


Listing discovered modules from CLI and/or Puppetfile:

    jhg03a/accountfacts


Installing modules. This may take a few minutes.
Calling 'puppet module install jhg03a/accountfacts --modulepath C:/Users/JONATH~1.GRA/AppData/Local/Temp/d20160503-12340-1qmhzw1 >/dev/null 2>&1 '
The system cannot find the path specified.
There was a problem with the module name 'jhg03a/accountfacts'.
  Check that module exists as you spelled it and/or your connectivity to the puppet forge.
```

**Comment by rnelson0** [comment]
I'm not sure how `mktemp` works on Windows. Did it create that directory?

**Comment by jhg03a** [comment]
Yep.  The output redirection may be the problem since /dev/null doesn't exist in windows.

**Comment by rnelson0** [comment]
Oh, good catch. I'll have to do some research on that.

-- 

Rob Nelson
rnelson0@gmail.com

**Comment by rnelson0** [comment]
@jhg03a I have a test of this in a branch but I don't have a windows box ready to test with. Can you try this for me? Point to `https://github.com/rnelson0/puppet-generate-puppetfile.git`, branch `windowsnull`. Thanks!

**Comment by rnelson0** [comment]
OK, that won't work. Back to the drawing board.

**Comment by rnelson0** [comment]
This is taken care of in #35. Please let me know if you have any other issues on Windows, I've not got a working environment for testing!

**Comment by rnelson0** [comment]
v0.9.9 published with this support.
