### ISSUE TITLE
Generated Puppetfile missing quotes around module name

### ISSUE THREAD

**Issue by djl** [rnelson0/puppet-generate-puppetfile#39]
When I run `generate-puppetfile` the output seems to lack quotes around the module name, resulting in an incorrect Puppetfile.

 For example:

    $ generate-puppetfile saz/sudo
    ... snip...
    mod puppetlabs/stdlib, '4.12.0'
    mod saz/sudo, '3.1.0'

I think this was introduced in e7d8bee1aa64706002a62bb53e7752d5d57b7e32.

**Comment by rnelson0** [comment]
Whoopsie! I'll look into fixing that now, thank you!

**Comment by rnelson0** [comment]
I released 0.9.10 with this fix, thanks!
