### ISSUE TITLE
Unsecure forge url for generated Puppetfile

### ISSUE THREAD

**Issue by skrysmanski** [rnelson0/puppet-generate-puppetfile#58]
I'm fairly new to Puppetfile, so forgive me if what I'm writing is rubbish. :)

When I call something like `generate-puppetfile puppetlabs-docker` the output will contain this line:

forge 'http://forge.puppetlabs.com'

This URL is not secure because it says `http` instead of `https`. 

Also, I think it should read `https://forge.puppet.com` nowadays (no longer `puppetlabs.com`).

I've found two occurrences of the *correct* URL in `bin.rb` - so I guess you've just overlooked this one.

**Comment by rnelson0** [comment]
Thank you for pointing this out!
